server/index-node: Fix missing `scalar Int` in the GraphQL schema
This was causing JS clients (such as indexer-service) to fail with the
following error:

    Error: Decorated type deeper than introspection query.

With this fix, that no longer happens.